name: e_absensi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.15.3
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  get: 4.6.6
  form_builder_validators: ^9.1.0
  flutter_svg: ^2.0.7
  local_auth: ^2.1.8
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

